name: Aikido Safe Chain - Malware Protection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  safe-chain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Aikido Safe Chain
        run: npm install -g @aikidosec/safe-chain

      - name: Setup Aikido Safe Chain
        run: safe-chain setup-ci

      - name: Install dependencies with Safe Chain protection
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
